LR_CROPPED_SIZE = 60 #100
UPSCALE = 4
HR_CROPPED_SIZE = UPSCALE * LR_CROPPED_SIZE

TRAIN_HR_DIR = "DIV2K/DIV2K_train_HR"
TRAIN_LR_DIR = f"DIV2K/DIV2K_train_LR_bicubic/X{UPSCALE}"
VAL_HR_DIR = "DIV2K/DIV2K_valid_HR"
VAL_LR_DIR = f"DIV2K/DIV2K_valid_LR_bicubic/X{UPSCALE}"

REAL_VALUE = 0.99
FAKE_VALUE = 0.0

BATCH_SIZE = 4 #16
EPOCHS = 50
WARMUP_EPOCHS = 0

N_RESBLK_G = 16
LR = 1e-4
# LR = 3e-4
BETAS = (0.5, 0.9)

VGG_LOSS_COEF = 0.006
ADVERSARIAL_LOSS_COEF = 0.001

# For Wasserstein Loss implementation
# CRITIC_ITERATIONS = 5
# WEIGHT_CLIP = 0.01
# WGAN_LR = 1e-5
# LAMBDA_GP = 10